// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.ceaser.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ceaser.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentList();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  StudentResponse getStudent(int index);
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentOrBuilderList();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  StudentResponseOrBuilder getStudentOrBuilder(
          int index);
}
