// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.ceaser.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ceaser.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  java.util.List<com.ceaser.proto.StudentResponse> 
      getStudentList();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  com.ceaser.proto.StudentResponse getStudent(int index);
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  java.util.List<? extends com.ceaser.proto.StudentResponseOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .com.ceaser.proto.StudentResponse student = 1;</code>
   */
  com.ceaser.proto.StudentResponseOrBuilder getStudentOrBuilder(
      int index);
}
